default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: export-poetry-reqs
        name: Export Poetry requirements.txt
        entry: |
          poetry export \
            --format=requirements.txt \
            --output=requirements.txt \
            --without-hashes
        language: system
        types: [python]
        stages: [pre-commit]
