#!/usr/bin/env bash

# Install Poetry
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

# Install project dependencies
/root/.poetry/bin/poetry install
